# WAFIR Configuration Example
# Place this file in .github/wafir.yaml in your repository

# Storage settings
storage:
  type: project # Options: issue, project, both
  # owner: optional-other-owner
  # repo: optional-other-repo

# Feedback settings
feedback:
  title: "Submit a Bug or Feature"
  labels: ["wafir", "user-feedback"]

# Issue settings (for automatic data collection)
issue:
  screenshot: false
  browserInfo: false
  consoleLog: false
  labels: ["bug"]

# Custom form fields
fields:
  - name: title
    label: "Issue Title"
    type: text
    required: true
  - name: description
    label: "Detailed Description"
    type: textarea
    required: true
  - name: priority
    label: "Priority"
    type: select
    options: ["Low", "Medium", "High", "Critical"]
    required: false

