/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initiate GitHub OAuth
         * @description Redirects to GitHub OAuth for user authorization
         */
        get: {
            parameters: {
                query: {
                    installationId: string;
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub OAuth Callback
         * @description Handles OAuth callback from GitHub
         */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status/{installationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Auth Status
         * @description Check if user token exists for installation
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    installationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            connected?: boolean;
                            installationId?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/{installationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect Auth
         * @description Remove stored user token for installation
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    installationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get WAFIR Configuration
         * @description Fetches and parses .github/wafir.yaml from the target repository.
         */
        get: {
            parameters: {
                query: {
                    installationId: number;
                    owner: string;
                    repo: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Modal title
                             * @default Contact Us
                             */
                            title: string;
                            storage?: {
                                /**
                                 * @default issue
                                 * @enum {string}
                                 */
                                type: "issue" | "project" | "both";
                                owner?: string;
                                repo?: string;
                                projectNumber?: number;
                            };
                            /** @description Automatic data collection settings */
                            telemetry?: {
                                /**
                                 * @description Enable screenshot capture
                                 * @default true
                                 */
                                screenshot: boolean;
                                /**
                                 * @description Collect URL, user agent, viewport, language
                                 * @default true
                                 */
                                browserInfo: boolean;
                                /**
                                 * @description Capture console messages
                                 * @default false
                                 */
                                consoleLog: boolean;
                            };
                            /** @description Widget tabs configuration. Defaults to feedback, suggestion, issue if omitted. */
                            tabs?: {
                                /** @description Unique tab identifier */
                                id: string;
                                /** @description Display label (defaults to capitalized id) */
                                label?: string;
                                /**
                                 * @description Tab icon
                                 * @enum {string}
                                 */
                                icon?: "thumbsup" | "lightbulb" | "bug";
                                /**
                                 * @description If true, rating from this tab populates project Rating field
                                 * @default false
                                 */
                                isFeedback: boolean;
                                /** @description Form fields for this tab. If omitted, defaults are used for known tab IDs (feedback, issue, suggestion) */
                                fields?: {
                                    /** @description Field ID/key for form data */
                                    name: string;
                                    /** @description Display label for the field */
                                    label: string;
                                    /**
                                     * @description Input type
                                     * @enum {string}
                                     */
                                    type: "text" | "email" | "textarea" | "select" | "checkbox" | "rating";
                                    /** @default false */
                                    required: boolean;
                                    placeholder?: string;
                                    /** @description Options for select type */
                                    options?: string[];
                                    /** @description Labels for each rating star (1-5) */
                                    ratingLabels?: string[];
                                }[];
                            }[];
                            /** @description Available issue types from the organization (auto-populated) */
                            issueTypes?: {
                                id?: number;
                                name?: string;
                                color?: string;
                            }[];
                            /** @description Dedicated project for feedback submissions with star ratings */
                            feedbackProject?: {
                                /** @description GitHub Project number for feedback */
                                projectNumber?: number;
                                /** @description Project owner (defaults to repo owner) */
                                owner?: string;
                                /**
                                 * @description Name of the Rating field in the project
                                 * @default Rating
                                 */
                                ratingField: string;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns the health status of the bridge service
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            timestamp?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback/Issue
         * @description Creates a new issue or project draft. Supports multipart/form-data.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
